name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubunt-latest]
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses:  actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and build webpack
      run: |
        npm install
        npm run build --if-present 
      env:
        CI: true

    - name: upload artifact
      uses: actions/upload-artifact@main
      with:
        name: webpack artifacts
        path: public/

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@main
      with:
        name: webpack artifacts
        path: public

    - name: Label when approved
      uses: pullreminders/label-when-approved-action@main
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"    
